### ISSUE TITLE
personal deck listing - no decks message

### ISSUE THREAD

**Issue by ahaurw01** [SirZach/bbbbbbbbbbbbbbb#101]
The personal decks page is not very inviting when you just sign up. Just a blank page. Some approach similar in spirit to this?

![screen shot 2015-05-07 at 9 14 47 pm](https://cloud.githubusercontent.com/assets/2068437/7528915/30717636-f4fe-11e4-9cd3-1422ca7f9b76.png)

**Comment by SirZach** [comment]
I was thinking there should be a nice big call to action on that empty page. Good idea.
