### ISSUE TITLE
design pattern: vertical "..." as menu on hover

### ISSUE THREAD

**Issue by ahaurw01** [SirZach/bbbbbbbbbbbbbbb#107]
What do you think about using the three dot menu for items that require a context menu? I was thinking this could be cool especially when we render cards in the game. Maybe the menu is something like "tap, add +1/+1 counter, move to > ,..." etc. It could also apply to things like the user's tile in the lobby if there are actions like "view profile, block", etc, who knows.

I love the way google music uses this pattern when you hover over album tiles:

![screen shot 2015-05-09 at 8 46 47 am](https://cloud.githubusercontent.com/assets/2068437/7550256/82065162-f628-11e4-8067-014afe4e958c.png)

![screen shot 2015-05-09 at 8 47 06 am](https://cloud.githubusercontent.com/assets/2068437/7550258/85bb53a2-f628-11e4-8d02-c9bb34f2ead0.png)

**Comment by SirZach** [comment]
I was holding off since this is an issue for the ember-paper project but I think we're at the point where we have to build our own ui kit. I think if we can adhere to the spec this should be easy. I built something like this for work recently

**Comment by SirZach** [comment]
I'm imagining the code usage being something like..
```htmlbars
{{#context-menu}}
 {{context-menu-item label="Tap" action="tapGameCard" param=card}}
{{/context-menu}}
```

And that would include the vertical '...' and all we have to do is just position the '...'

**Comment by ahaurw01** [comment]
Yeah, could be. Haven't really thought through how we might want to separate the concerns of what items show up in the menu and where the menu component would exist in the markup. But, yeah, something along those lines! Curious to see what you've made for work.

**Comment by SirZach** [comment]
That's more or less what I've made for work. I'm completely open to a new approach though. Admittedly my mind closes up to new ideas once I've made it before in a certain way.

**Comment by SirZach** [comment]
is reliant upon #114 to pave the way for the first context-menu needed on the library zone

**Comment by SirZach** [comment]
check out https://github.com/miguelcobain/ember-paper/tree/material-menus this branch has context menus!

**Comment by SirZach** [comment]
first pass built in #135
