### ISSUE TITLE
Orphan presences can stick around

### ISSUE THREAD

**Issue by ahaurw01** [SirZach/bbbbbbbbbbbbbbb#11]
Quick fix: don't render orphan presences.

Idea to investigate: my hunch is that these are from old sessions that are connecting again. E.g. you sleep your laptop while connected, then come back and it's in a weird state somehow. Just an idea.

**Comment by ahaurw01** [comment]
Another idea is to embed the presence stuff within the user model to cut down on complexity. Not sure if that'll actually fix the problem or not.

**Comment by SirZach** [comment]
good to close this?

**Comment by ahaurw01** [comment]
Yeah, let's close for now. If it comes back with a vengeance, we can reopen.
