### ISSUE TITLE
implement card search for library context

### ISSUE THREAD

**Issue by SirZach** [SirZach/bbbbbbbbbbbbbbb#134]
spawned from #115

**Comment by ahaurw01** [comment]
Possibly this is to address the comment I made in https://github.com/SirZach/bbbbbbbbbbbbbbb/pull/138 about the library cards opening up as soon as you click anywhere on the library zone or on the library context menu.

**Comment by SirZach** [comment]
I have this fixed on a branch :) do you think that's how card search should
work? Just open the game-zone and no modal?

**Comment by ahaurw01** [comment]
Oh awesome. Not sure, that's one idea. Wasn't sure how we wanted to
increase visibility for cards in those zones as a whole. They can be pretty
small depending on the viewport size. Did you have some ideas?

**Comment by SirZach** [comment]
It would honestly not be terrible to implement the modal, it may actually be easier but it wouldn't be consistent with how the other game-zones are doing it. I would only be just slightly sad to use a modal for all the game zones but i can deal. Another option could be sliding out an area like the toggle filters and just shoving cards in that area. Might be a little shocking but it would allow us to have full-sized cards no matter what viewport you were using.

**Comment by SirZach** [comment]
i can try implementing this in the slide-in area and see how it feels

**Comment by SirZach** [comment]
Turns out the slide-in will require how that game page is laid out. I'm excited to fix this. The use of fixed positioning means that it doesn't slide over, or at least not with the current set of styles. I made good progress last night switching the game play and game chat over to a flex display. Yay flex.
