### ISSUE TITLE
Deck list filters

### ISSUE THREAD

**Issue by ahaurw01** [SirZach/bbbbbbbbbbbbbbb#141]
Throw in some toggled filters like we have on the deck building page.

* Author
* Mine only?
* Deck name
* Colors

We can create another ticket for 1.0 to add more filters if only a couple of these are tackled.

**Comment by SirZach** [comment]
:+1:

**Comment by SirZach** [comment]
closing this. can re-open with filters in mind for a 1.0 or later release
