### ISSUE TITLE
Site hijacks browser's back button

### ISSUE THREAD

**Issue by jimmycougar** [SirZach/bbbbbbbbbbbbbbb#192]
using chrome on iPad, back button has no effect. webatrice.com redirects to webatrice.com/games/list and back button will not return to previous page (even spamming the back button)

**Comment by ahaurw01** [comment]
Thanks! I think due to `transitionTo` instead of `replaceWith`:
https://github.com/SirZach/bbbbbbbbbbbbbbb/blob/master/app/routes/index.js#L11

Possibly this is a problem elsewhere we might be redirecting.

**Comment by ahaurw01** [comment]
@jimmycougar, could you try things out again to make sure this update did the trick?

**Comment by jimmycougar** [comment]
@ahaurw01 It works correctly in chrome on Win7, I'll give it a try tonight on the iPad. Sorry for the slow response, I signed up for github with my spam email so I don't get notifications immediately.

**Comment by jimmycougar** [comment]
@ahaurw01 Fix verified!

**Comment by ahaurw01** [comment]
Woohoo! Thanks! No worries about the delay.

**Comment by SirZach** [comment]
@jimmycougar forward emails from your spam email coming from github to your good email. you're important to us and we want to make sure we can get in touch! also thanks for creating a github account on our behalf :8ball:
