### ISSUE TITLE
Disclaimer page is rife with typos and grammar errors

### ISSUE THREAD

**Issue by jimmycougar** [SirZach/bbbbbbbbbbbbbbb#199]
Okay, maybe not rife.

> unaffilicated

> is TM and copyright Wizards of the Coast

Also it is ugly.

**Comment by Createor** [comment]
Any update on this fix?

**Comment by ahaurw01** [comment]
No work done yet. Been some busy times for the contributors. I'm sure some quick fixes will do plenty here. PRs always welcome :smile:

**Comment by SirZach** [comment]
This has been fixed.
