### ISSUE TITLE
Deck edit page takes a long time to load

### ISSUE THREAD

**Issue by ahaurw01** [SirZach/bbbbbbbbbbbbbbb#221]
It seems like this is from populating the list of cards under the search box with what we currently have in the store. I'm not sure having any cards already showing is useful at all since you have to search anyway to find what you want.

How do you feel about not showing any cards when you first load that page and instead a message telling you to search?

**Comment by SirZach** [comment]
I like that approach as long as yes - we definitely need some helper text to help them get going. Definitely  an autofocus on that text box.

In the future it would be cool to show, by default, the most recently added cards.

Also - we're only loading 20 cards, right? I'm not sure why that's causing such a performance impact

**Comment by SirZach** [comment]
@ahaurw01 not experiencing performance issues on the deck edit page. are you still seeing something not right?

**Comment by SirZach** [comment]
*bump*

**Comment by ahaurw01** [comment]
Now that we're not loading all cards from all decks just to see the deck picture, there isn't much to load now on the edit page. I'm cool to close this.
