### ISSUE TITLE
Using a code styler like JSCS

### ISSUE THREAD

**Issue by SirZach** [SirZach/bbbbbbbbbbbbbbb#225]
@ahaurw01 I like how the ember codebase looks identical no matter which file you're in. They utilize http://jscs.info/ to enforce that. There's an ember addon, ember-suave, that enforces the same code style rules that ember core uses. If you're on board, I'd like to make use of this as well.

**Comment by ahaurw01** [comment]
This sound fine to me! I've been using eslint mostly at work and that seems to be working well, but it looks like this is maybe more geared toward code style than syntax linting, possibly. Hopefully it won't make a ton of work for getting everything whipped into shape. I'm all for trying it out!

**Comment by SirZach** [comment]
Awesome. I have a huge PR coming your way soon...
