### ISSUE TITLE
move cards model fetch out of the application route

### ISSUE THREAD

**Issue by SirZach** [SirZach/bbbbbbbbbbbbbbb#30]
this is preventing the loading screen from showing up. this means having to duplicate the cards fetch in the deck and cards route.

**Comment by ahaurw01** [comment]
SGTM. Kinda crazy idea, but is the cards route really necessary?

**Comment by SirZach** [comment]
i had glorious plans of an awesome card browser that wouldn't be tied to deck building or game playing but just a straight-up pleasant card viewing experience. the cards page was supposed to solve this.

**Comment by ahaurw01** [comment]
Gotcha. Ignore the heretic.
