### ISSUE TITLE
upgrade to glimmer

### ISSUE THREAD

**Issue by SirZach** [SirZach/bbbbbbbbbbbbbbb#95]
Glimmer just landed on ember-canary. Let's upgrade to it and feel the wrath of that which is rendering speed!

**Comment by ahaurw01** [comment]
This gif feels right for some reason.

![YES](http://media.giphy.com/media/xLqMFR72mIZ0c/giphy.gif)

**Comment by SirZach** [comment]
I think the reason is pretty damn obvious :)

**Comment by SirZach** [comment]
currently blocked by https://github.com/ef4/liquid-fire/issues/276

**Comment by SirZach** [comment]
blocked by https://github.com/miguelcobain/ember-paper/issues/86
