### ISSUE TITLE
public deck list

### ISSUE THREAD

**Issue by ahaurw01** [SirZach/bbbbbbbbbbbbbbb#99]
- start by sorting newest first?

**Comment by ahaurw01** [comment]
I keep wanting to start this, then keep getting annoyed by the thought of yet another pagination/continuous scrolling "list everything in the world" feature. What do you think about starting with just the ability to view a certain user's decks? Something like `/decks/SirZach` or maybe `/profiles/SirZach` which lists your decks and could do more things down the road?

**Comment by SirZach** [comment]
The <code>/profiles/ahaurw01</code> is a nice idea. What I liked about the public deck list page is that you don't need to be knowledgeable of users in order to find decks. It will destroy our firebase throughput though so I am a little worried about scaling and how much that'll cost.
